### ISSUE TITLE
Crashes when running compiled build (part 2)

### ISSUE THREAD

**Issue by craigmit** [NaluKit/gwt-maven-springboot-archetype#15]
Using the same instructions in https://github.com/NaluKit/gwt-maven-springboot-archetype/issues/13

We still crash:
```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 20: C:/a/mywebapp/nested:/C:/a/mywebapp/mywebapp-server/target/mywebapp.war/!WEB-INF/classes/!/launcherDir
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:166)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:98)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at com.mycompany.mywebapp.Application$EmbeddedServletContainerConfig.customize(Application.java:40)
        at com.mycompany.mywebapp.Application$EmbeddedServletContainerConfig.customize(Application.java:32)
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.lambda$postProcessBeforeInitialization$0(WebServerFactoryCustomizerBeanPostProcessor.java:72)
        at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$0(LambdaSafe.java:287)
        at org.springframework.boot.util.LambdaSafe$LambdaSafeCallback.invoke(LambdaSafe.java:159)
        at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$1(LambdaSafe.java:286)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
        at org.springframework.boot.util.LambdaSafe$Callbacks.invoke(LambdaSafe.java:286)
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:72)
        at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.postProcessBeforeInitialization(WebServerFactoryCustomizerBeanPostProcessor.java:58)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
        ... 23 more
```

**Comment by FrankHossfeld** [comment]
Thanks for creating the PR!
